--- #YAML:1.0
name:               Nagios-Status-HostStatus
version:            0.01
abstract:           Nagios 3.0 Class to maintain Hosts' Status.
author:
    - Roy Crowder <rcrowder@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Nagios::Status::Host:  0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
